name: kadhir_OffPolicy
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.14.1
  - aiohttp=3.7.4.post0
  - async-timeout=3.0.1
  - attrs=21.2.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.10.26
  - cachetools=4.2.4
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.2
  - cloudpickle=1.6.0
  - cryptography=3.4.7
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - dataclasses=0.8
  - dbus=1.13.6
  - dill=0.3.4
  - expat=2.4.1
  - ffmpeg=4.3.2
  - fontconfig=2.13.1
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.19.8.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - grpcio=1.38.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gym=0.19.0
  - icu=58.2
  - idna=3.1
  - importlib-metadata=4.8.1
  - intel-openmp=2021.3.0
  - jpeg=9b
  - kiwisolver=1.3.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libpng=1.6.37
  - libprotobuf=3.18.1
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - multidict=5.2.0
  - ncurses=6.2
  - nettle=3.6
  - ninja=1.10.2
  - numpy=1.20.3
  - numpy-base=1.20.3
  - oauthlib=3.1.1
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pcre=8.45
  - pillow=8.3.1
  - pip=21.2.4
  - protobuf=3.18.1
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyglet=1.5.16
  - pyjwt=2.2.0
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyzmq=22.3.0
  - qt=5.9.7
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.7.1
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - tbb=2021.4.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.0
  - tk=8.6.11
  - torchaudio=0.10.0
  - torchfile=0.1.0
  - torchvision=0.11.1
  - tornado=6.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021b
  - urllib3=1.26.7
  - visdom=0.1.8.9
  - websocket-client=0.57.0
  - werkzeug=2.0.1
  - wheel=0.37.0
  - x264=1!161.3030
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yarl=1.7.0
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - nn-builder==0.0.12
    - pandas==1.3.4
    - pytz==2021.3
    - torch-tb-profiler==0.3.0
